apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/default-pod/
patchesStrategicMerge:
- ./kind-default-patch.yaml
images:
- name: default-api-image
  newName: default-api-amd64
  newTag: "1.0"
